### ISSUE TITLE
TEMUL simulations through PyPrismatic

### ISSUE THREAD

**Issue by EileenAtoms** [PinkShnack/TEMUL#18]
Hi @PinkShnack 

PyPrismatic has undergone an update from 1.1.16 to 0.2.1
The update has disturbed some of the TEMUL functionality, through name changes of functions etc

simulations.py needs some updating

Thnks,
Eileen

**Comment by PinkShnack** [comment]
Indeed! I will probably make an issue on the PyPrismatic GitHub.
Cheers for the notice!

**Comment by PinkShnack** [comment]
This will be handled in #46 in so much as the newest changes in pyprismatic will be useable.
