### ISSUE TITLE
polarisation Colormap legend

### ISSUE THREAD

**Issue by Kalanimo** [PinkShnack/TEMUL#28]
the colormaps are great for displaying polarisation but when you add the legend, it onlt has the colours with the angles lablelled.
Could you add arrows in the colourbar beside the labels to make it more intuitive pleaseee

**Comment by PinkShnack** [comment]
I will look into it now :)
Thanks for the good idea! 

Though if I can't do it, I think the way you did it in your paper through powerpoint would be suitable for publications.

**Comment by PinkShnack** [comment]
Closing this because it is probably a lot of work for not much payoff. Also, as I mentioned, we can easily do it in another graphical software for the few graphs in which we need this kind of labelling.
